### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mel-liow** [UBC-MDS/airpyllution#43]
- [x] Deploy by ReadTheDocs
- [x] Use napolean Sphinx extension
- [x] Add demonstration of each function
- [x] Add plots to README to demonstrate function outputs in the Usage section
- [x] Add codecov badge to README

[![codecov](https://codecov.io/gh/UBC-MDS/airpyllution/branch/main/graph/badge.svg?token=c6vEGpbs3h)](https://codecov.io/gh/UBC-MDS/airpyllution)
[![build](https://github.com/UBC-MDS/airpyllution/actions/workflows/build.yml/badge.svg)](https://github.com/UBC-MDS/airpyllution/actions/workflows/build.yml)
[![deploy](https://github.com/UBC-MDS/airpyllution/actions/workflows/deploy.yml/badge.svg)](https://github.com/UBC-MDS/airpyllution/actions/workflows/deploy.yml)
```
[![codecov](https://codecov.io/gh/UBC-MDS/airpyllution/branch/main/graph/badge.svg?token=c6vEGpbs3h)](https://codecov.io/gh/UBC-MDS/airpyllution)
[![build](https://github.com/UBC-MDS/airpyllution/actions/workflows/build.yml/badge.svg)](https://github.com/UBC-MDS/airpyllution/actions/workflows/build.yml)
[![deploy](https://github.com/UBC-MDS/airpyllution/actions/workflows/deploy.yml/badge.svg)](https://github.com/UBC-MDS/airpyllution/actions/workflows/deploy.yml)
```

**Comment by danfke** [comment]
Draft has been created for the readthedocs page: https://airpyllution.readthedocs.io/

I'm running into a few problems. 

The first is that the API key shouldn't be visible in the documentation, which I don't think should be too hard to fix I just need to import it in from a different file I think.

The second problem is my plotly plots aren't working in html for some reason. I've tried using a few different renderers including the notebook renderer which should work with offline html. Next think I'll try is exporting the plot to a separate html and then embedding it back into the documentation html. If I can't get it to work I will just render it as a static png, but that is unideal because the point of the documentation is to show what our functions can do.

Third problem is just an aesthetic one, @christopheralex 's plot is way too big and is going off the page. I think he's working on a solution.

Also if anyone knows how to hide cells in a notebook that would be useful but not super important. I've tried adding tags to the cells to hide them and also tried editing their metadata but neither worked.

**Comment by mel-liow** [comment]
First point, yeah - i think this will involve setting up a config.env (or something similar) which should be added to `.gitignore`.
There should be a way of then reading in this file to get the `api_key`.

RE the last point, you might have already seen this but I managed to hide code cells in notebooks by going through this doc: https://myst-nb.readthedocs.io/en/latest/use/hiding.html

**Comment by christopheralex** [comment]
Third point , I just need to modify the properties in my code to a suitable image size .

**Comment by christopheralex** [comment]
Do you guys want a 4*2 matrix plot or 3 rows with 3,3,2 set up ?

**Comment by christopheralex** [comment]
Going with 3,3,2 set up to match R package.
