### ISSUE TITLE
License Discussion

### ISSUE THREAD

**Issue by danfke** [UBC-MDS/airpyllution#53]
What are your opinions on our license? Is it odd that someone can sell our software if they wanted to? Also, if there's a possibility that someone could use our software for nefarious purposes should we switch to the hippocratic license?

**Comment by christopheralex** [comment]
I was thinking on the lines of the GNU license because it forces collaborators to give credit at every change but like Tiff said maybe it puts off collaborators and they refrain from collaborating . 
Since we are at the initial stage of our package where collaborations are key for improvement, I think we can go ahead with hippocratic license which also addresses unethical practices using our package. 
What about license for our documents ?

**Comment by danfke** [comment]
Not sure what you mean by license for the documents. Doesn't everything in the package fall under the same license?

**Comment by christopheralex** [comment]
Never mind , we do not have any PPT in our documents in our repo . If we did we might have to include another license as the above licenses are only for code written.

**Comment by mel-liow** [comment]
I'm also happy with us sticking to the MIT license too actually as it's well known amongst the compsci/ data science community so users would probably be more comfortable contributing to the package because they're more familiar with it. But, having read the hippocratic license, I like that it embodies ethical source principals and it's nice to know our package can't be used for unethical activities

**Comment by danfke** [comment]
I agree with the above sentiments. The MIT license provides our package with the openness and accessibility that we envisioned it to have while protecting us from liability. However, I agree with the mission statement behind the Hippocratic license, and since it provides the same openness and protection as the MIT license while also providing terms against unethical behaviour for users of our package, I prefer the Hippocratic license. Furthermore, I think its values align with the values that we as the authors of the package have and the values that underlie the motivation behind our package, making it an appropriate license for airpyllution/rpollution.
